### ISSUE TITLE
Cannot install the app on Windows 11

### ISSUE THREAD

**Issue by nikraychev** [open-condo-software/open-condo-platform#49]
PS C:\Apache24\htdocs\condo> node ./bin/prepare.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- C:\Apache24\htdocs\condo\bin\prepare.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Apache24\htdocs\condo\bin\prepare.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Apache24\\htdocs\\condo\\bin\\prepare.js' ]
}

Node.js v20.10.0
PS C:\Apache24\htdocs\condo> npm install commander
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./domains

npm ERR! A complete log of this run can be found in: C:\Users\profn\AppData\Local\npm-cache\_logs\2023-12-05T14_03_43_574Z-debug-0.log
PS C:\Apache24\htdocs\condo> npm install file:./domains
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Apache24\htdocs\condo\domains/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Apache24\htdocs\condo\domains\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\profn\AppData\Local\npm-cache\_logs\2023-12-05T14_09_46_422Z-debug-0.log
PS C:\Apache24\htdocs\condo> npm install file:./apps/address-service/domains
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./domains

npm ERR! A complete log of this run can be found in: C:\Users\profn\AppData\Local\npm-cache\_logs\2023-12-05T14_11_23_026Z-debug-0.log
PS C:\Apache24\htdocs\condo> npm install file:./apps/address-service/domains
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @app/address-service@1.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.13.1" from @app/address-service@1.0.0
npm ERR!   apps/address-service
npm ERR!     @app/address-service@1.0.0
npm ERR!     node_modules/@app/address-service
npm ERR!       workspace apps\address-service from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from @keystonejs/fields-color@1.1.2
npm ERR! node_modules/@keystonejs/fields-color
npm ERR!   @keystonejs/fields-color@"^1.1.0" from @app/address-service@1.0.0
npm ERR!   apps/address-service
npm ERR!     @app/address-service@1.0.0
npm ERR!     node_modules/@app/address-service
npm ERR!       workspace apps\address-service from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\profn\AppData\Local\npm-cache\_logs\2023-12-05T14_13_17_509Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\profn\AppData\Local\npm-cache\_logs\2023-12-05T14_13_17_509Z-debug-0.log
PS C:\Apache24\htdocs\condo> npm install file:./apps/address-service/domains --force
npm WARN using --force Recommended protections disabled.
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

npm ERR! A complete log of this run can be found in: C:\Users\profn\AppData\Local\npm-cache\_logs\2023-12-05T14_14_29_580Z-debug-0.log
PS C:\Apache24\htdocs\condo> yarn workspace @app/condo build
Internal Error: root@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at TR.getCandidates (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1715982)
    at wd.getCandidates (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1613543)
    at C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1729504
    at Lg (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1574940)
    at r (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1729483)
    at async Promise.allSettled (index 0)
    at async go (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1574276)
    at async C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1730139
    at async di.startProgressPromise (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1611268)
    at async ze.resolveEverything (C:\Apache24\htdocs\condo\.yarn\releases\yarn-3.2.2.cjs:2:1728223)

**Comment by toplenboren** [comment]
Hi! This app doesn't work on windows. You can try WSL or Linux

**Comment by kelemenbalazs** [comment]
Also node v20 is not supported. Use Node v16
